### ISSUE TITLE
Support Parameters in Product Endpoints

### ISSUE THREAD

**Issue by decaffeintedWonk** [ConsumerDataStandardsAustralia/banking-products-comparator#107]
**Description**
Community feedback around the Banking Product Comparator (BPC) tool includes support for Parameters in the Query for each of the Product endpoints; main focus is on the Get Products API. Some Data Holders have a number of brands included in their endpoints and want to filter by these for the BPC tool. Additional functionality will also allow consumers to test their endpoints on the tool.

**Related Work Items**
   - #1 Update data model to include a URL customisation via parameters
   - #2 Store user provided parameters (preferred), preferred: datasources.json
   - #3 Default values when a value is not provided OR defer back to current URI behaviour
   - #4 Error handling and parsing when incorrect/ faulty parameters are provided
   - #5 UI Upgrades to support presentation to consumers
   - #6 Support customisation for some Data Holders and defaults for others
   - #7 Update documentation on Readme.md about adding in Parameters
   - #8 Add guide

**Comment by decaffeintedWonk** [comment]
Will close this issue for now - these features do not belong in a Comparator Product per se but rather a tool which focuses on validating a payload from an endpoint.

**Comment by JoeGunnion** [comment]
Hi 
Just checking if there was any update regarding this - using parameters such as brand and page-size.
Thanks,
Joseph
