### ISSUE TITLE
Product eligibility array key

### ISSUE THREAD

**Issue by nils-rbal** [ConsumerDataStandardsAustralia/banking-products-comparator#11]
I think the 'eligibilities' key [here](https://github.com/ConsumerDataStandardsAustralia/banking-products-comparator/blob/d0324839f660c235fa97a60ea25c16cafca6aebf/src/utils/dict.js#L140) may be incorrect.
Current standard describes '[eligibility](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingproductdetail)' array.

**Comment by vadkor** [comment]
Fixed.
