### ISSUE TITLE
Add Illawarra Credit Union Products

### ISSUE THREAD

**Issue by IllawarraCU** [ConsumerDataStandardsAustralia/banking-products-comparator#117]
Hi,

Please add Illawarra Credit Union to the comparator site with the details below.

{
"name": "Illawarra Credit Union",
"url": "https://onlineteller.cu.com.au/OpenBanking/cds-au/v1",
"icon": "https://www.illawarracu.com.au/content/themes/nucleo-icu/assets/images/logo.png"
}

Thanks

**Comment by CDR-API-Stream** [comment]
Hi @IllawarraCU ,

Thanks for your interest and contribution, however we need to verify your request before we action it. If you could please send a note verifying this Github profile and issue to: cdr-data61@csiro.au ?

Once verified, the team can work on adding your endpoint to the Banking Product Comparator.

Thanks,
