### ISSUE TITLE
Add The Capricornian Ltd to Comparitor

### ISSUE THREAD

**Issue by ShaneCullen155** [ConsumerDataStandardsAustralia/banking-products-comparator#122]
Hello,

Hi,

Please add The Capricornian Ltd to the comparator site with the details below.

{
"name": "The Capricornian Ltd",
"url": "https://onlinebanking.capricornian.com.au/OpenBanking/cds-au/v1/banking/products",
"icon": "https://www.capricornian.com.au/wp-content/themes/capricornian/images/capricornian-logo.png"
}

Thank you,

Shane

**Comment by CDR-API-Stream** [comment]
Hi @ShaneCullen155 

Thanks for raising the request. We do need to verify your association with The Capricornian Ltd, could you please send a note to the contact@consumerdatastandards.gov.au 

Once we have verified we will proceed with the changes requestd.

Thanks,
Data Standards Body team

**Comment by vadkor** [comment]
@ShaneCullen155, we've created a pull request #123 on your behalf. Please note that we've put a corrected base URL in it: https://onlinebanking.capricornian.com.au/OpenBanking/cds-au/v1

Also, please be aware that currently your endpoints don't support CORS and return 405 on OPTIONS, so won't work in the Comparator.
