### ISSUE TITLE
Add The Capricornian Ltd to Comparitor

### ISSUE THREAD

**Issue by ShaneCullen155** [ConsumerDataStandardsAustralia/banking-products-comparator#126]
Hello,

Please add The Capricornian Ltd to the comparator site with the details below.

{
"name": "The Capricornian Ltd",
"url": "https://onlinebanking.capricornian.com.au/OpenBanking/cds-au/v1",
"icon": "https://www.capricornian.com.au/wp-content/themes/capricornian/images/capricornian-logo.png"
}

Our core banking software provider completed an update which should resolve the following;

Also, please be aware that currently your endpoints don't support CORS and return 405 on OPTIONS, so won't work in the Comparator.

Hoping this will be ok.

Thanks,

Shane

**Comment by vadkor** [comment]
Hi. No need to raise a new issue. Your base URL is added since #122, which was closed when the linked pull request was merged.
Your endpoints do support CORS now. However, the status and outages endpoints return 500.

**Comment by ShaneCullen155** [comment]
Hello Vadkor,

I've communicated the information above to our software vendor.  They have advised the following;

I have just tested the prod endpoint and it returns product list as expected: https://onlinebanking.capricornian.com.au/OpenBanking/cds-au/v1/banking/products 
It works on the comparator as well. Please refer to the screens below. 

The 500 error (server not available) indicated that the response from Ultracs did not contain complete information.

Can they please specify how do they get the 500 error and what is the endpoint? It might be a DEV? 

Could you provide more information about how you were receiving the 500 error?

Thanks,

Shane

**Comment by vadkor** [comment]
@ShaneCullen155, https://onlinebanking.capricornian.com.au/OpenBanking/cds-au/v1/banking/products is only one of the four endpoints the Comparator calls using your base URL. Two of them are product endpoints (list and details) and the other two are discovery (status and outages). Refresh your Comparator page if you don't see the Status And Outages tab in it. The 500 response status that your discovery endpoints return on GET is not "Server not available", it is "Internal server error". You can see these error in the web browser Developer Tools, in the Network tab. Also there are errors in the Console tab. Your vendor should know these things.
