### ISSUE TITLE
Upgrade react-scripts to 3.4.^

### ISSUE THREAD

**Issue by liamgib** [ConsumerDataStandardsAustralia/banking-products-comparator#15]
**Description**
I had an error running the application with react-scripts at 3.3.0.
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

After manually bringing the react-scripts to 3.4.0, the error was resolved.

This application is a great demonstration of the standards, thank you.

**Comment by vadkor** [comment]
Cannot reproduce. Cloned the repo into a new directory (and freshly installed yarn with no local packages downloaded), `yarn` and `yarn start`. No errors. Platform: Linux, Windows.

**Comment by liamgib** [comment]
Tested with yarn, I can confirm there are no errors, and the application functions as expected.
Although, if I delete the provided yarn-lock.json file on a clean clone and install - The application gives the same error as mentioned on `yarn start`.

I provisioned a cleaned VM on Vultr (Ubuntu 18.04 x64) and installed NPM, and can confirm the same error is being displayed.

**Comment by vadkor** [comment]
Wow! People still use `npm` in this century! :-) Please don't remove the lock files - they are manually updated to the latest security recommendations.
The fix is merged to the master and is available at https://consumerdatastandardsaustralia.github.io/banking-products-comparator/
