### ISSUE TITLE
Macquarie Credit Union Limited dropping off comparator website

### ISSUE THREAD

**Issue by MacquarieCU** [ConsumerDataStandardsAustralia/banking-products-comparator#167]
Hi there,

We have been adding our ADI to the comparator website manually for over a week now and every morning when checking if the changes saved it keeps dropping off the comparator site. Our core banking supplier has advised there is no issue on there end as once added we can compare the products and have suggested raising a ticket here. Are you able to add to the website to ensure compliance. Details are as follows;

Name: Macquarie Credit Union Limited
URL: https://banking.macquariecu.com.au/OpenBanking

Kind regards
Matt

**Comment by CDR-API-Stream** [comment]
Hi @MacquarieCU ,

Thanks for the question and the usage of the Product Comparator.

If you're adding the new URL in the Product Comparator then, unfortunately, it is only adding this to your local browser and not to the data file. Hence why it does not appear the next day. The DSB are happy to add this to the data file and what Macquaire Credit Union can do is raise an Issue (just as you have done here) with the following details (copy and paste the below if it helps):
{
"name": "<name-of your-organisation>",
"url": "https://banking.macquariecu.com.au/OpenBanking”,
"icon": "<macquarie-bank-url>"
}

A great example is this Issue #100 if that helps guide you. There are some guides here: https://cdr-support.zendesk.com/hc/en-us/sections/900000747466-Banking-Product-Comparator on the CDR Support Portal which may assist you as well.

If you still have trouble, please reach out to contact@consumerdatastandards.gov.au and we'll assist.
-Jarryd

**Comment by MacquarieCU** [comment]
Hi Jarryd, thanks for the info, I have submitted a new issue now with reference to your comment. Let me know if i need to add anything else.

Kind regards
Matt
