### ISSUE TITLE
Please add Orange Credit Union to the comparator website

### ISSUE THREAD

**Issue by OrangeCreditUnion** [ConsumerDataStandardsAustralia/banking-products-comparator#176]
Our details are:

Orange Credit Union Limited - Brand

{
"name": "Orange Credit Union Limited",
"url": "https://banking.orangecu.com.au/openbanking"
"icon": ""
}

**Comment by Mause** [comment]
That domain doesn't seem to have any records?

**Comment by LukePrior** [comment]
I'm running into the same issue when trying:

`curl -X GET https://banking.orangecu.com.au/openbanking/cds-au/v1/banking/products -H "x-v: 3"`

The existing URL I had on file was: https://online.orangecu.com.au/cds-au/v1/banking/products however that has been down for months. This URL was taken from the banks website here: https://www.orangecu.com.au/tools-a-faq-open-banking.html

I tried making contact with you at ocu@orangecu.com.au on the 5th of August to ask about the issue but haven't heard anything back.

I should not that I have absolutely no relation to this project and am simply commenting here as it is the only avenue I could find.

Cheers

**Comment by Mause** [comment]
It looks like they tried to submit an issue 22 days ago, but weren't familiar with the github UI? With the current URL however

https://github.com/OrangeCreditUnion/banking-products-comparator/blob/patch-1/Orange%20Credit%20Union%20dropping%20off%20comparator%20website

**Comment by tom-schier** [comment]
@OrangeCreditUnion We are trying encourage community engagement. Could you please create a PR for this? This also makes better traceability between issues and code changes. Thanks

**Comment by OrangeCreditUnion** [comment]
Hi Thomas,
            Thanks for your email.

            I am unfamiliar with using Git Hub. Can you please advise what a PR is & how I would create this?

Glenn Tracey
Head of Growth Initiatives and Credit Risk
[Logo, company name  Description automatically generated]

288 Summer Street, PO Box 992, Orange NSW 2800
Ph. 02 6391 5260    0413 491 152
***@***.******@***.***>    orangecu.com.au<http://orangecu.com.au/>

ABN 34 087 650 477. AFSL 240768. Australian Credit Licence 240768. BSB 802-129

[Icon  Description automatically generated]<https://www.facebook.com/orangecreditunion>[Icon  Description automatically generated]<https://www.instagram.com/orangecreditunion/>[Icon  Description automatically generated]<https://www.youtube.com/channel/UCGsY3YCGN95OqXHGqU2hO7w>[Icon  Description automatically generated]<https://www.linkedin.com/company/orange-credit-union>

WARNING: This email and any files transmitted with it are confidential, intended solely for the use of the individual or entity to whom they are addressed. This communication may contain protected material. If you are not the intended recipient, be advised that you have received this email in error and that any use, dissemination, forwarding, printing or copying of this email is strictly prohibited.
Orange Credit Union will never send you a link that directly opens our Internet Banking page. Always type www.orangecu.com.au<http://www.orangecu.com.au/> into your browser or use our Mobile Banking App. to securely access your accounts. For more information, visit www.orangecu.com.au/stay-safe<http://www.orangecu.com.au/stay-safe>. Before accessing emails or the Internet, always ensure your computer has up-to-date security software. Never disclose your account access information such as, PINs, passwords and one-time passcodes. If you suspect any suspicious activity on your accounts, please contact us immediately on 6362 4466 or call the Orange Credit Union Fraud Team on 1300 705 750.

**Comment by tom-schier** [comment]
@OrangeCreditUnion Not to worry. If you are unfamiliar we will do this for you.

**Comment by OrangeCreditUnion** [comment]
Hi,
            Perfect thank you.

Glenn Tracey
Head of Growth Initiatives and Credit Risk
[Logo, company name  Description automatically generated]

288 Summer Street, PO Box 992, Orange NSW 2800
Ph. 02 6391 5260    0413 491 152
***@***.******@***.***>    orangecu.com.au<http://orangecu.com.au/>

ABN 34 087 650 477. AFSL 240768. Australian Credit Licence 240768. BSB 802-129

[Icon  Description automatically generated]<https://www.facebook.com/orangecreditunion>[Icon  Description automatically generated]<https://www.instagram.com/orangecreditunion/>[Icon  Description automatically generated]<https://www.youtube.com/channel/UCGsY3YCGN95OqXHGqU2hO7w>[Icon  Description automatically generated]<https://www.linkedin.com/company/orange-credit-union>

WARNING: This email and any files transmitted with it are confidential, intended solely for the use of the individual or entity to whom they are addressed. This communication may contain protected material. If you are not the intended recipient, be advised that you have received this email in error and that any use, dissemination, forwarding, printing or copying of this email is strictly prohibited.
Orange Credit Union will never send you a link that directly opens our Internet Banking page. Always type www.orangecu.com.au<http://www.orangecu.com.au/> into your browser or use our Mobile Banking App. to securely access your accounts. For more information, visit www.orangecu.com.au/stay-safe<http://www.orangecu.com.au/stay-safe>. Before accessing emails or the Internet, always ensure your computer has up-to-date security software. Never disclose your account access information such as, PINs, passwords and one-time passcodes. If you suspect any suspicious activity on your accounts, please contact us immediately on 6362 4466 or call the Orange Credit Union Fraud Team on 1300 705 750.

**Comment by OrangeCreditUnion** [comment]
Hi,
            Thank you. I will follow up with our IT supplier & come back to you as soon as I can.

Glenn Tracey
Head of Growth Initiatives and Credit Risk
[Logo, company name  Description automatically generated]

288 Summer Street, PO Box 992, Orange NSW 2800
Ph. 02 6391 5260    0413 491 152
***@***.******@***.***>    orangecu.com.au<http://orangecu.com.au/>

ABN 34 087 650 477. AFSL 240768. Australian Credit Licence 240768. BSB 802-129

[Icon  Description automatically generated]<https://www.facebook.com/orangecreditunion>[Icon  Description automatically generated]<https://www.instagram.com/orangecreditunion/>[Icon  Description automatically generated]<https://www.youtube.com/channel/UCGsY3YCGN95OqXHGqU2hO7w>[Icon  Description automatically generated]<https://www.linkedin.com/company/orange-credit-union>

WARNING: This email and any files transmitted with it are confidential, intended solely for the use of the individual or entity to whom they are addressed. This communication may contain protected material. If you are not the intended recipient, be advised that you have received this email in error and that any use, dissemination, forwarding, printing or copying of this email is strictly prohibited.
Orange Credit Union will never send you a link that directly opens our Internet Banking page. Always type www.orangecu.com.au<http://www.orangecu.com.au/> into your browser or use our Mobile Banking App. to securely access your accounts. For more information, visit www.orangecu.com.au/stay-safe<http://www.orangecu.com.au/stay-safe>. Before accessing emails or the Internet, always ensure your computer has up-to-date security software. Never disclose your account access information such as, PINs, passwords and one-time passcodes. If you suspect any suspicious activity on your accounts, please contact us immediately on 6362 4466 or call the Orange Credit Union Fraud Team on 1300 705 750.

**Comment by OrangeCreditUnion** [comment]
Hi,
            We have confirmed with our IT supplier that the URL https://online.orangecu.com.au/openbanking/<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fonline.orangecu.com.au%2fopenbanking%2f&umid=f5030118-c20e-41fc-b564-7bd24c581e5b&auth=b29328f7d6f3ffca05b11f97830962e9fc9fd327-d4ec14bb05345e45811b01681766b2b48819f0cb> is correct. We have been able to retrieve our product details form the comparator website as per below.


            However our details will drop off the site. We have confirmed that by logging onto the comparator  site from another PC that our details do not appear. Can you please alter so that our details remain on the site.




***@***.***

Glenn Tracey
Head of Growth Initiatives and Credit Risk
[Logo, company name  Description automatically generated]

288 Summer Street, PO Box 992, Orange NSW 2800
Ph. 02 6391 5260    0413 491 152
***@***.******@***.***>    orangecu.com.au<http://orangecu.com.au/>

ABN 34 087 650 477. AFSL 240768. Australian Credit Licence 240768. BSB 802-129

[Icon  Description automatically generated]<https://www.facebook.com/orangecreditunion>[Icon  Description automatically generated]<https://www.instagram.com/orangecreditunion/>[Icon  Description automatically generated]<https://www.youtube.com/channel/UCGsY3YCGN95OqXHGqU2hO7w>[Icon  Description automatically generated]<https://www.linkedin.com/company/orange-credit-union>

WARNING: This email and any files transmitted with it are confidential, intended solely for the use of the individual or entity to whom they are addressed. This communication may contain protected material. If you are not the intended recipient, be advised that you have received this email in error and that any use, dissemination, forwarding, printing or copying of this email is strictly prohibited.
Orange Credit Union will never send you a link that directly opens our Internet Banking page. Always type www.orangecu.com.au<http://www.orangecu.com.au/> into your browser or use our Mobile Banking App. to securely access your accounts. For more information, visit www.orangecu.com.au/stay-safe<http://www.orangecu.com.au/stay-safe>. Before accessing emails or the Internet, always ensure your computer has up-to-date security software. Never disclose your account access information such as, PINs, passwords and one-time passcodes. If you suspect any suspicious activity on your accounts, please contact us immediately on 6362 4466 or call the Orange Credit Union Fraud Team on 1300 705 750.

From: Glenn Tracey
Sent: Monday, 11 October 2021 11:52 AM
To: 'ConsumerDataStandardsAustralia/banking-products-comparator' ***@***.***>; ConsumerDataStandardsAustralia/banking-products-comparator ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [ConsumerDataStandardsAustralia/banking-products-comparator] Please add Orange Credit Union to the comparator website (#176)

Hi,
            Thank you. I will follow up with our IT supplier & come back to you as soon as I can.

Glenn Tracey
Head of Growth Initiatives and Credit Risk
[Logo, company name  Description automatically generated]

288 Summer Street, PO Box 992, Orange NSW 2800
Ph. 02 6391 5260    0413 491 152
***@***.******@***.***>    orangecu.com.au<http://orangecu.com.au/>

ABN 34 087 650 477. AFSL 240768. Australian Credit Licence 240768. BSB 802-129

[Icon  Description automatically generated]<https://www.facebook.com/orangecreditunion>[Icon  Description automatically generated]<https://www.instagram.com/orangecreditunion/>[Icon  Description automatically generated]<https://www.youtube.com/channel/UCGsY3YCGN95OqXHGqU2hO7w>[Icon  Description automatically generated]<https://www.linkedin.com/company/orange-credit-union>

WARNING: This email and any files transmitted with it are confidential, intended solely for the use of the individual or entity to whom they are addressed. This communication may contain protected material. If you are not the intended recipient, be advised that you have received this email in error and that any use, dissemination, forwarding, printing or copying of this email is strictly prohibited.
Orange Credit Union will never send you a link that directly opens our Internet Banking page. Always type www.orangecu.com.au<http://www.orangecu.com.au/> into your browser or use our Mobile Banking App. to securely access your accounts. For more information, visit www.orangecu.com.au/stay-safe<http://www.orangecu.com.au/stay-safe>. Before accessing emails or the Internet, always ensure your computer has up-to-date security software. Never disclose your account access information such as, PINs, passwords and one-time passcodes. If you suspect any suspicious activity on your accounts, please contact us immediately on 6362 4466 or call the Orange Credit Union Fraud Team on 1300 705 750.

**Comment by OrangeCreditUnion** [comment]
Thank you issue resolved

Glenn Tracey
Head of Growth Initiatives and Credit Risk
[Logo, company name  Description automatically generated]

288 Summer Street, PO Box 992, Orange NSW 2800
Ph. 02 6391 5260    0413 491 152
***@***.******@***.***>    orangecu.com.au<http://orangecu.com.au/>

ABN 34 087 650 477. AFSL 240768. Australian Credit Licence 240768. BSB 802-129

[Icon  Description automatically generated]<https://www.facebook.com/orangecreditunion>[Icon  Description automatically generated]<https://www.instagram.com/orangecreditunion/>[Icon  Description automatically generated]<https://www.youtube.com/channel/UCGsY3YCGN95OqXHGqU2hO7w>[Icon  Description automatically generated]<https://www.linkedin.com/company/orange-credit-union>

WARNING: This email and any files transmitted with it are confidential, intended solely for the use of the individual or entity to whom they are addressed. This communication may contain protected material. If you are not the intended recipient, be advised that you have received this email in error and that any use, dissemination, forwarding, printing or copying of this email is strictly prohibited.
Orange Credit Union will never send you a link that directly opens our Internet Banking page. Always type www.orangecu.com.au<http://www.orangecu.com.au/> into your browser or use our Mobile Banking App. to securely access your accounts. For more information, visit www.orangecu.com.au/stay-safe<http://www.orangecu.com.au/stay-safe>. Before accessing emails or the Internet, always ensure your computer has up-to-date security software. Never disclose your account access information such as, PINs, passwords and one-time passcodes. If you suspect any suspicious activity on your accounts, please contact us immediately on 6362 4466 or call the Orange Credit Union Fraud Team on 1300 705 750.
