### ISSUE TITLE
Please update the base address of MyState Bank

### ISSUE THREAD

**Issue by kaichiuwong** [ConsumerDataStandardsAustralia/banking-products-comparator#177]
**Description**
Please update the base address of MyState Bank 
_From_ 
{"name": "MyState Bank", "url": "https://openbanking.api.mystate.com.au/public"},
_to_
{"name": "MyState Bank", "url": "https://openbank.api.mystate.com.au"},

**Comment by CDR-API-Stream** [comment]
Hi @kaichiuwong thanks for the Issue.

Could you please send a verification email to: contact@consumerdatastandards.gov.au so we can verify your association with MyState Bank? After we will merge your request in.

Thanks,

**Comment by kaichiuwong** [comment]
Hi @CDR-API-Stream,

Thanks for your comment. I have sent an email to contact@consumerdatastandards.gov.au to confirm my linkage with MyState Bank. Thanks.

Kai
