### ISSUE TITLE
Please update a logo URL for MyState Bank

### ISSUE THREAD

**Issue by kaichiuwong** [ConsumerDataStandardsAustralia/banking-products-comparator#179]
**Description**
Please add the logo URL for MyState Bank in public/datasources.json

**Related Work Items**
_Update from_ 
 {"name": "MyState Bank", "url": "https://openbank.api.mystate.com.au"},
_to_
 {"name": "MyState Bank", "url": "https://openbank.api.mystate.com.au", "icon": "https://mystate.com.au/wp-content/uploads/MyState_Logo_s.png"},

**Comment by tom-schier** [comment]
@kaichiuwong We are trying encourage community engagement. Could you please create a PR for this? This also makes better traceability between issues and code changes. Thanks

**Comment by kaichiuwong** [comment]
Thanks @tom-schier. A pull request has been created.
https://github.com/ConsumerDataStandardsAustralia/banking-products-comparator/pull/180
