### ISSUE TITLE
Question regarding heroku deployment

### ISSUE THREAD

**Issue by mukeshrijhwani** [ConsumerDataStandardsAustralia/banking-products-comparator#18]
Hi there, 

Thanks for the brilliant comparator. 
For testing, I deployed the code on Heroku. 

I got the following error: 

`code=H10 desc="App crashed" method=GET path="/banking-products-comparator" host=XXXXX.herokuapp.com request_id=35353-8f70-4a06-aaec-1f0eb1d512f7 fwd="XX.XXX.XXX.XXX" dyno= connect= service= status=503 bytes= protocol=https`

Any help will be appreciated. 
Thanks
Mukesh

**Comment by CDR-API-Stream** [comment]
Hi @mukeshrijhwani ,

We don't develop or support Heroku as part of our product offered here; it's only used as our CORS mechanism. For your error the following user guide might be helpful (looking at your error code H10) [here](https://dev.to/lawrence_eagles/causes-of-heroku-h10-app-crashed-error-and-how-to-solve-them-3jnl#:~:text=This%20error%20is%20thrown%20if,App%20crashed%20error%20code%20message.)

We suggest getting this running on your local machines as per our instructions here in the readme.md file: https://github.com/ConsumerDataStandardsAustralia/banking-products-comparator 

Good luck with setting & running the Product Comparator Tool.

Thanks,
-Data Standards Body Team
