### ISSUE TITLE
Please add product URLs to comparator - Bendigo and Adelaide Bank

### ISSUE THREAD

**Issue by Mekaal** [ConsumerDataStandardsAustralia/banking-products-comparator#33]
Hi All

Could we please have the following added to the comparator:

Name: Bendigo Bank;  Base url: https://api.cdr.bendigobank.com.au/cds-au/v1
Name: Adelaide Bank;  Base url: https://api.cdr.adelaidebank.com.au/cds-au/v1
Name: Rural Bank;  Base url:  https://api.cdr.ruralbank.com.au/cds-au/v1
Name: Delphi Bank;  Base url:  https://api.cdr.delphibank.com.au/cds-au/v1
Name:  Leveraged;  Base url:  https://api.cdr.leveraged.com.au/cds-au/v1
Name:  AWA Alliance Bank;  Base url:  https://api.cdr.awaalliancebank.com.au/cds-au/v1
Name:  BDCU Alliance Bank;  Base url:  https://api.cdr.bdcualliancebank.com.au/cds-au/v1
Name:  Circle Alliance Bank;  Base url:  https://api.cdr.circle.com.au/cds-au/v1
Name:  Nova Alliance Bank;  Base url:  https://api.cdr.novaalliancebank.com.au/cds-au/v1
Name:  Service One Alliance Bank;  Base url:  https://api.cdr.serviceone.com.au/cds-au/v1

Thank-you

**Comment by perlboy** [comment]
All of these endpoints contain non conformant payloads. Over 500 errors in total.

Notable ones are non compliant DurationString's for rates of FIXED type, for instance Adelaide Bank:
![image](https://user-images.githubusercontent.com/4291448/89977503-9b87a600-dcae-11ea-9db9-dbe5b913fe85.png)
