### ISSUE TITLE
Add Heritage Bank to Comparitor

### ISSUE THREAD

**Issue by pjones-hbs** [ConsumerDataStandardsAustralia/banking-products-comparator#42]
Hi,

Could we please have Heritage added to the comparator:

Name: Heritage Bank
Base URL: https://product.api.heritage.com.au/cds-au/v1/

Thanks,
Paul.

**Comment by vadkor** [comment]
Hi Paul. We encourage the community to fork the repo, make the additions / fixes / improvements themselves and submit the cross-repo pull requests. Here is an example: #25
