### ISSUE TITLE
Support OTHER Fee Type

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/banking-products-comparator#56]
**Description**
Comparator does not currently support the recently added `OTHER` fee type.

**Comment by JamesMBligh** [comment]
Thanks @perlboy, we'll look to add this after java-artefacts is updated to 1.5.0 and the the status/outage enhancement is completes.

Are there any other fields missing that you're aware of that would be useful?

**Comment by vadkor** [comment]
I assume @perlboy meant _VARIABLE_ FeeType.
