### ISSUE TITLE
Add LCU Products

### ISSUE THREAD

**Issue by matt31330** [ConsumerDataStandardsAustralia/banking-products-comparator#63]
Please add Laboratories Credit Union to the comparator site, details below. 
{
"name": "Laboratories Credit Union",                         
"url": "https://internetbanking.lcu.com.au/openbanking/cds-au/v1",                         
"icon": "https://asset.lcu.com.au/images/StandardLCULogo-nobackground.png"
}  

Thanks

**Comment by vadkor** [comment]
@matt31330, If you haven't sent one yet, please email us at cdr-data61@csiro.au to verify your association with LCU and your change will be merged.
