### ISSUE TITLE
Add First Option Bank Products

### ISSUE THREAD

**Issue by alexvladica** [ConsumerDataStandardsAustralia/banking-products-comparator#68]
Please add First Option Bank to the comparator site, details below.
{
"name": "First Option Bank",
"url": "https://internetbanking.firstoption.com.au/OpenBanking/cds-au/v1/", 
"icon": "https://firstoptionbank.com.au/wp-content/uploads/2020/06/FO_Bank_logo_black.png"
}

**Comment by vadkor** [comment]
Please note the correct URL is https://internetbanking.firstoption.com.au/OpenBanking/cds-au/v1 (no trailing slash), but even that won't work in the Comparator since you haven't implemented CORS.

**Comment by vadkor** [comment]
@alexvladica, If you haven't sent one yet, please email us at cdr-data61@csiro.au to verify your association with First Option Bank and your change will be merged.

**Comment by alexvladica** [comment]
HI @vadkor 
I will email now, and check on the CORS setup
