### ISSUE TITLE
Add QBANK URI

### ISSUE THREAD

**Issue by qbankit** [ConsumerDataStandardsAustralia/banking-products-comparator#70]
Hi,

Please add QBANK to the comparator site, details below.

{
"name": "QBANK",
"url": "https://banking.qbank.com.au/openbanking/cds-au/v1",
"icon": "https://www.qbank.com.au/getmedia/a76807cb-5d38-478a-83d5-b6fc2acc7fa7/QBank_150.png.aspx"
}

Kind regards

**Comment by vadkor** [comment]
@qbankit, If you haven't sent one yet, please email us at cdr-data61@csiro.au to verify your association with QBANK and your change will be merged.
