### ISSUE TITLE
Auswide Bank URI  - Live

### ISSUE THREAD

**Issue by AuswideBank** [ConsumerDataStandardsAustralia/banking-products-comparator#74]
Can you please load Auswide onto the Comparator Tool
{
"name": "Auswide Bank",                         
"url": "https://api.auswidebank.com.au/OpenBanking/cds-au/v1/banking/products",                         
"icon": "https://www.auswidebank.com.au/resources/images/templates/shared/auswide-bank-logo.png"    
}

**Comment by vadkor** [comment]
As commented on your PR #65, we are waiting for your email to us at cdr-data61@csiro.au to verify the association of your GitHub persona with the bank. Once we receive it your PR will be merged.

If you need to change the URL and don't want us to merge PR #65, let us know.
