### ISSUE TITLE
Unable to add a pull request for banking-products-comparator

### ISSUE THREAD

**Issue by BARithikaP** [ConsumerDataStandardsAustralia/banking-products-comparator#88]
**Description**
Would like to include Bank Australia Public Product APIs in the DSB comparator site. Please find the code below as I’m unable to add a pull request in github. Happy to lodge the request via Github if you can tell me how. The pull request icon remains greyed out. 

**Related Work Items**
    - #1 
{
"name": "Bank Australia",                         
"url": "https://cds.api.bankaust.com.au/cds-au/v1/banking/products",                         
"icon": "https://www.bankaust.com.au/globalassets/assets/imagery/logos/bank-australia/ba-horizontal-logo.png"    
}

**Comment by vadkor** [comment]
Raised PR: #91
